#!/bin/bash
#
# This script is used to deploy the CloudFormation stack for monitoring
# ONTAP system.
################################################################################
#
################################################################################
# This function just prints the usage of the script and exits.
################################################################################
usage () {
  cat <<EOF >&2
Usage: $(basename $0) [-R Region>] -b <s3Bucket> -F <FSxNListFilename> -s <subnets> -g <securityGroup> -t <snsTopicArn> -a <secretArnPattern> [-v <checkInterval>] [-w <true|false>] [-r <monitoringRoleArn>] [-x <controlRoleArn>] [-l <lambdaLayerArn>] [-m maxRunTime] [-M memorySize] [-f <cloudformationUrl>]
    -R <region> The AWS region where the AWS resources are located. Optional, defaults to the region configured in the AWS CLI.
    -b <bucket> The S3 bucket where the CloudFormation template is stored
    -F <FSxNListFilename> The name of the file in the S3 bucket that containing the list of FSxN systems to monitor.
    -s <subnets> Comma-separated list of subnet IDs (not ARNs).
    -g <securityGroup> The security group ID to use (not ARN). Just needs to allow outbound over TCP port 443.
    -t <snsTopicArn> The ARN of the SNS topic for notifications.
    -a <secretArnPattern> The secrets ARN pattern that will match all the serects that the monitoring function will use to for FSxN credentials.
    -v <checkInterval> The interval in minutes to check the ONTAP system (optional, the default is 15 minutes).
    -w <true|false> Create CloudWatch watchdog alarms (optional, default is true).
    -r <moniotoringRoleArn> The Arn of the role to use for the Monitoring Lambda function (optional).
    -x <controllerRoleArn> The Arn of the role to use for the Controller Lambda function (optional).
    -l <lambdaLayerArn> The ARN of the Lambda layer to use (optional).
    -W <webhookEndpoint> The endpoint to send notifications to (optional).
    -m <maxRunTime> The maximum run time for the monitoring function in seconds (optional). Must be between 60 and 900. Defaults to 60.
    -M <memorySize> The amount of memory to allocate to the monitoring function in MB (optional). Must be between 128 and 10240. Defaults to 128.
    -f <cloudformationUrl> The URL of the CloudFormation template (optional). Should be in the form of: https://s3.<AWSregion>.amazonaws.com/<bucketName>/cloudformation.yaml
EOF
  exit 1
}

################################################################################
# Main code starts here.
################################################################################
#
# Process command line arguments.
watchdog="true"
checkInterval=15
maxRunTime=60
memorySize=128
region=$(aws configure get region)
if [ -z "$region" ]; then
  region="$AWS_DEFAULT_REGION"
fi
if [ -z "$region" ]; then
  region="$AWS_REGION"
fi

while getopts "hR:b:F:S:s:g:t:a:v:w:r:x:l:W:m:M:f:" opt; do
  case $opt in
    R) region="$OPTARG" ;;
    b) bucket="$OPTARG" ;;
    F) FSxNListFilename="$OPTARG" ;;
    S) FSxNStatusFilename="$OPTARG" ;;
    s) subnets="'$OPTARG'" ;;
    g) securityGroup="$OPTARG" ;;
    t) snsTopicArn="$OPTARG" ;;
    a) secretArnPattern="$OPTARG" ;;
    v) checkInterval="$OPTARG" ;;
    w) watchdog="$(echo $OPTARG | tr '[A-Z]' '[a-z]')" ;;
    r) mointoringRoleArn="$OPTARG" ;;
    x) controllerRoleArn="$OPTARG" ;;
    l) lambdaLayerArn="$OPTARG" ;;
    W) webhookEndpoint="$OPTARG" ;;
    m) maxRunTime="$OPTARG" ;;
    M) memorySize="$OPTARG" ;;
    f) cloudformationUrl="$OPTARG" ;;
    *) usage ;;
  esac
done

if [ -z "$FSxNListFilename" -o -z "$bucket" -o -z "$subnets" -o -z "$securityGroup" -o -z "$snsTopicArn" -o -z "$secretArnPattern" ]; then
  echo "Error: Missing required arguments." >&2
  usage
fi

if [ -z "$region" ]; then
  echo "Error: AWS region not specified and not configured in AWS CLI." >&2
  exit 1
fi

if [ $watchdog != "true" -a $watchdog != "false" ]; then
  echo "Error: Invalid value for -w option. Use 'true' or 'false'." >&2
  usage
fi
#
# Create a CloudFormation stack name that isn't too long.
stackName=MOS-multi-$$

if [ -r "$FSxNListFilename" ]; then
  if aws s3 --region $region cp $FSxNListFilename s3://$bucket; then
    :
  else
    echo "Error, could not copy FSxNList file '$FSxNListFilename' to S3 bucket." >&2
    echo "Exiting..." >&2
    exit 1
  fi
fi
#
# The script got too big now it has to be stored in a S3 bucket.
if [ -z "$cloudformationUrl" ]; then
  if aws s3 --region $region cp cloudformation.yaml s3://$bucket; then
    cloudformationUrl="https://s3.${region}.amazonaws.com/${bucket}/cloudformation.yaml"
  else
    echo "Error, could not copy cloudformation.yaml to S3 bucket." >&2
    echo "Exiting..." >&2
    exit 1
  fi
fi
#
# Since the only reason to provide a watchdog role ARN is to attach it to the Lambda function
# that it will use to publish the SNS topic. Otherwise, assume the watchdog ClouedWatch
# alarm will publish to the topic directly.
if [ ! -z "$watchdogRoleArn" ]; then
  implementWatchdogAsLambda="true"
else
  implementWatchdogAsLambda="false"
fi
#
# Deploy the stack
aws cloudformation create-stack --region $region --stack-name $stackName --template-url $cloudformationUrl \
  --capabilities CAPABILITY_NAMED_IAM --parameters \
  ParameterKey=s3BucketName,ParameterValue=$bucket \
  ParameterKey=FSxNListFilename,ParameterValue=$FSxNListFilename \
  ParameterKey=subNetIds,ParameterValue="$subnets" \
  ParameterKey=securityGroupIds,ParameterValue=$securityGroup \
  ParameterKey=snsTopicArn,ParameterValue=$snsTopicArn \
  ParameterKey=createWatchdogAlarm,ParameterValue="$watchdog" \
  ParameterKey=implementWatchdogAsLambda,ParameterValue="$implementWatchdogAsLambda" \
  ParameterKey=watchdogRoleArn,ParameterValue="$watchdogRoleArn" \
  ParameterKey=checkInterval,ParameterValue="$checkInterval" \
  ParameterKey=lambdaLayerArn,ParameterValue="$lambdaLayerArn" \
  ParameterKey=monitoringRoleArn,ParameterValue="$monitoringRroleArn" \
  ParameterKey=controllerRoleArn,ParameterValue="$controllerRroleArn" \
  ParameterKey=maxRunTime,ParameterValue="$maxRunTime" \
  ParameterKey=memorySize,ParameterValue="$memorySize"
