---
#
# This workflow will run terraform validate if any of the terraform files are
# changed in the specified directories.
#
name: "Code Quality: Terraform"

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'FSx_Alerting/Auto-Add-CloudWatch-Alarms/terraform/**'
      - 'FSx_Alerting/FSx_ONTAP_Alerting/terraform/**'
  push:
    paths:
      - 'FSx_Alerting/Auto-Add-CloudWatch-Alarms/terraform/**'
      - 'FSx_Alerting/FSx_ONTAP_Alerting/terraform/**'
    branches:
      - main

jobs:
  #
  # Since there is no way to know which paths triggered the event
  # we are going to use the 'dorny' utility to do it.
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      auto_add_cloudwatch_alarms: ${{ steps.filter.outputs.auto_add_cloudwatch_alarms }}
      fsx_ontap_alerting: ${{ steps.filter.outputs.fsx_ontap_alerting }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Check for path changes
        id: filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        with:
          filters: |
            auto_add_cloudwatch_alarms:
              - 'FSx_Alerting/Auto-Add-CloudWatch-Alarms/terraform/**'
            fsx_ontap_alerting:
              - 'FSx_Alerting/FSx_ONTAP_Alerting/terraform/**'

  auto_add_cw_alarms:
    name: auto_add_cw_alarms
    runs-on: ubuntu-latest
    needs: check-paths
    if: ${{ needs.check-paths.outputs.auto_add_cloudwatch_alarms == 'true' }}

    defaults:
      run:
        working-directory: 'FSx_Alerting/Auto-Add-CloudWatch-Alarms/terraform'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout pull request
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # v1.4.0
        with:
          terraform_wrapper: false
          terraform_version: 1.12.1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

  fsxn_alerting:
    name: fsxn_alerting
    runs-on: ubuntu-latest
    needs: check-paths
    if: ${{ needs.check-paths.outputs.fsx_ontap_alerting == 'true' }}

    defaults:
      run:
        working-directory: 'FSx_Alerting/FSX_ONTAP_Alerting/terraform'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout pull request
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # v1.4.0
        with:
          terraform_wrapper: false
          terraform_version: 1.12.1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate
